name: finsight
description: Financial insight assistant by Maxint Inc.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  adaptive_breakpoints: ^0.1.7
  collection: ^1.18.0
  csv: ^6.0.0
  envied: ^0.5.4+1
  file_picker: ^8.0.0+1
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.2.4
  google_fonts: ^6.2.1
  google_generative_ai: ^0.3.0
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  material_symbols_icons: ^4.2719.3
  path: ^1.9.0
  path_provider: ^2.1.3
  salomon_bottom_bar: ^3.3.2
  sliver_tools: ^0.2.12
  very_good_infinite_list: ^0.7.1
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  supabase_flutter: ^2.5.2
  fluentui_system_icons: ^1.1.236
  intl: ^0.19.0
  auto_size_text: ^3.0.0
  url_launcher: ^6.2.6
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  fonts:
    - family: BC Alphapipe
      fonts:
        - asset: fonts/BC-Alphapipe-L-Regular.ttf
        - asset: fonts/BC-Alphapipe-TSB-Bold.ttf
          weight: 700