name: finsight
description: Financial insight assistant by Maxint Inc.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  collection: ^1.18.0
  csv: ^6.0.0
  envied: ^0.5.4+1
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.2.4
  google_generative_ai: ^0.3.0
  hooks_riverpod: ^2.5.1
  material_symbols_icons: ^4.2719.3
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
