name: Build
on:
  workflow_dispatch: 

env:
  FLUTTER_VERSION: 3.19.5
  FLUTTER_CHANNEL: stable

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4.0.0  
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: subosito/flutter-action@v2.10.0
        with:
          cache: true
          channel: ${{ env.FLUTTER_CHANNEL}}
          flutter-version: ${{ env.FLUTTER_VERSION  }}
      
      - name: Install apt deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev make fakeroot strace fuse libunwind-dev locate patchelf

      - name: Create .env
        shell: bash
        run: |
          envsubst < .env.example > .env
      
      - name: Generating files with build_runner
        run: |
          dart run build_runner build --delete-conflicting-outputs

      - name: Build android apks
        run: |
          flutter build apk
          mkdir -p dist
          mv build/app/outputs/flutter-apk/app-release.apk dist/Finsight-android-all.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: Finsight-Release-Binaries
          path: |
            dist/Finsight-android-all.apk

      - name: Debug With SSH When fails
        if: ${{ failure() && inputs.debug }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true